### ISSUE TITLE
Update to Exiled 6

### ISSUE THREAD

**Issue by itsmewio** [skyyt15/SpectatorToScp#1]
I loooveeedd this Plugin, it was such a helpfull Plugin. Players loved it. 
A Update to Exiled 6 will be very cool, because its a very good plugin!

**Comment by skyfr0676** [comment]
Hello ! 
Thank you for you answer !
I'm working on it this afternoon !

**Comment by itsmewio** [comment]
I Hope u dont forget it 😅

**Comment by skyfr0676** [comment]
Noooo, don't worry, I've updated the plugin but I don't have anyone to try it and that's what takes time

**Comment by skyfr0676** [comment]
Oops

**Comment by itsmewio** [comment]
You can ask me😌

**Comment by itsmewio** [comment]
You can ask me😌

**Comment by skyfr0676** [comment]
hey @itsmewio !
https://github.com/skyyt15/SpectatorToScp/releases/tag/V2.0.0 ^^
